### ISSUE TITLE
Mimic Tool - Request

### ISSUE THREAD

**Issue by feelgooddd** [ArachisH/Tanji#1]
Mimic tool if possible to copy anyones looks in the room by clicking them and hitting mimic or their name in a drop down box on Tanji

**Comment by ArachisH** [comment]
It's been a month since this request, but yea, sounds like a good idea.

**Comment by otraore** [comment]
http://github.com/adversities/mmimic He  said he'll port it to V1 as well.

**Comment by ClockDev** [comment]
@otraore Yeah was gonna say, there's extensions for this too haha

**Comment by ArachisH** [comment]
Sorry to say, but I've decided to not add these types of "for fun" tools in Tanji itself.
