### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by ovladuk** [ArachisH/Tanji#10]
might be a dumb question but how exactly do you use this? thought it was with python or tampermonkey but nope! any help?

**Comment by ArachisH** [comment]
You can download the latest binaries here: https://github.com/ArachisH/Tanji/releases/latest
This application only works in the Windows OS, and you will also need to install the [.NET Framework 4.7.1 Runtime](https://www.microsoft.com/en-us/download/details.aspx?id=56116) if you do not have it already.

Then you just open **Tanji.exe**, allow the root certificate to be installed(if first time), click **Connect**, and login/open the game client.
