### ISSUE TITLE
Packet Loop/Lifespan

### ISSUE THREAD

**Issue by Kupla** [ArachisH/Tanji#11]
It would be very nice if we can really script.
I mean something

```
loop 8 times:
   send package "x"
   wait 1500ms
```

Or instead that simply tool that would help us send one package wait and send second package etc.

**Comment by ArachisH** [comment]
This would be a nice addition to the Scheduler tool. You mean to only send the data X amount of times, then stop while going at a specific interval?

**Comment by Speaqer** [comment]
Great idea!

**Comment by Kupla** [comment]
Yes. You can set delay between packages and loop forever until you stop (or press hotkey) or just loop x times. This would be helpful to trade and cancel trade automatically, sit and stand fast (would be funny dance) etc.

**Comment by ArachisH** [comment]
I just finished this:
![Scheduler](http://i.imgur.com/4stE4Gm.png)
It sends a packet 8 times before it stops, each being sent withing 1500 ms of each other. Is this what you wanted, or was it a bit more different?

**Comment by ArachisH** [comment]
I guess I'll considered this closed.
