### ISSUE TITLE
Tanji will not work by my 

### ISSUE THREAD

**Issue by xFemkex** [ArachisH/Tanji#16]
If i start Tanji than after a 3 seconds say he: error! and message: Could not load type, can can you help my? the screen what I see: http://postimg.org/image/6l80u7c6v/

**Comment by Speaqer** [comment]
Update your .NET framework, it should fix that.

**Comment by xFemkex** [comment]
wait a hour or more, my pc where Tanji on is, is now updating

**Comment by xFemkex** [comment]
After 1000 years bullshit, he works, but if I start Tanji, load the retro hotel not more :(

**Comment by Speaqer** [comment]
Retro support is removed from newest Tanji versions. Check Tanji v1.3.794 or older for retro support.
