### ISSUE TITLE
No reaction

### ISSUE THREAD

**Issue by Wizdien90** [ArachisH/Tanji#17]
Hi, I have a problem with tanji 1.4 when I open it (with administrator rights) and I press on "Connect" there is nothing going on that's just "Extracting Game Data ..." in the end I logged in to Habbo without  Tanji but you can help me?

**Comment by Speaqer** [comment]
Did you do it in this order? 
1. Click "Connect" button. 
2. Then log in to habbo. 
3. After logging in open hotel window and after this you need to wait little bit 'cos Tanji is doing stuff..
4. When packetlogger pops up, you're connected.

**Comment by ArachisH** [comment]
Ensure no proxy/VPN is running.

**Comment by Wizdien90** [comment]
Thanks You !
