### ISSUE TITLE
I see not connect button

### ISSUE THREAD

**Issue by xFemkex** [ArachisH/Tanji#18]
I download v1.3.794 because a person say to my, that Tanji version 1.3.794 or older, only work on retro hotels, but be I blind, or where is the connect button? http://imgur.com/5Xb2NNX

**Comment by Speaqer** [comment]
Make sure you downloaded "Tanji.zip" and not source code. 
Here's download link for the Tanji: https://github.com/ArachisH/Tanji/releases/tag/v1.3.794.0

**Comment by xFemkex** [comment]
I think that my Framework the problem is, framework say: No acces, to a delete object: http://postimg.org/image/e2x3t0xdt/

**Comment by Speaqer** [comment]
What .NET Framework version you have?

**Comment by xFemkex** [comment]
4.5 since yesterday

**Comment by Speaqer** [comment]
Can you click "Details" and then send screenshot.

**Comment by xFemkex** [comment]
Is one screen enough? http://postimg.org/image/ez42zf3gh/
