### ISSUE TITLE
No injection in the client

### ISSUE THREAD

**Issue by Wizdien90** [ArachisH/Tanji#20]
i've followed the instructions : 
- When i'm to the enter i press connect 
- Then i go in the client
- Tanji put " Extracting game data " 

But the problem there isn't injection , i've disabled proxy and all .. but i can't fix that 
can you help me please .

I don't have this problem with tanji 1.3.794.0 if you can't find solution can you fix the problems with .dll file with tanji 1.3.794.0 'cause i can't open file in .dll with this release just files in .exe .
Thanks you again and excuze me for my english i'm french

**Comment by Speaqer** [comment]
I think Arachis doesn't provide support for older Tanji versions anymore. Ask help for your problem at http://sulakore.com
