### ISSUE TITLE
Never Connect

### ISSUE THREAD

**Issue by Dtonadorr** [ArachisH/Tanji#29]
I have been trying to connect Tanji to Habbo for many days, but I have had no results. Either Tanji doesn't recognize Habbo, and is showing the message '' intercepiting client page '', or Tanji goes to the next step but Habbo doesn't connect. I don't use any type of VPN

Things I've tried to do during the days of research to find an answer to this:

Updated Java and NET FrameWork

I used the RunTimes program

I modified the host

I used 5 different browsers

Anyway, I tried everything they recommended and absolutely nothing happens. I am trying for the last time now through this forum, otherwise I will consider the program a lie.

Details about my PC: Windows 10, 64 bits, x64

**Comment by ArachisH** [comment]
- Tanji only requires runtime .NET 4.7.2(and up).
- Please do not modify the hosts file when attempting to connect with Tanji, as it could mess up the connection process(Tanji does not require hosts file modification).
- Ensure you are using the latest release of Tanji, as of today it will be 1.4.1390.
- Do not try running Tanji as administrator, this could cause weird side-effects when installing the self-signed certificate authority.

If you have TeamViewer I will be willing to assist you through it, either shoot me a PM on discord(Arachis#9488) or through my email(iKBenPeanut@gmail.com).

**Comment by ArachisH** [comment]
Program is lie
