### ISSUE TITLE
tanji intercepting client

### ISSUE THREAD

**Issue by QairexStudio** [ArachisH/Tanji#30]
tanji has error intercepting client page thatsnt fixing. how can i fix it ?

**Comment by Guiviniac** [comment]
I also have the same problem, did you manage to fix it?

**Comment by QairexStudio** [comment]
> I also have the same problem, did you manage to fix it?

No i'm was tried habbo retro and Habbo but Doesnt still working.

**Comment by QairexStudio** [comment]
> I also have the same problem, did you manage to fix it?

İf still continue same problem i will make my own Habbo sniffer. i just need to learn program logic.

**Comment by ArachisH** [comment]
Make sure any VPN/Proxy browser extension is completely **disabled**. Even if the extension is just off, it could still interfere with the 'Intercepting Client' step.

**Comment by QairexStudio** [comment]
> Make sure any VPN/Proxy browser extension is completely **disabled**. Even if the extension is just off, it could still interfere with the 'Intercepting Client' step.

Bruh why you wasnt reply my question at 24 days ago

**Comment by QairexStudio** [comment]
> Make sure any VPN/Proxy browser extension is completely **disabled**. Even if the extension is just off, it could still interfere with the 'Intercepting Client' step.

And thanks i will try it later

**Comment by ArachisH** [comment]
I'm too lazy to troubleshoot the problems of all the users honestly, I just do this for fun.

**Comment by QairexStudio** [comment]
> I'm too lazy to troubleshoot the problems of all the users honestly, I just do this for fun.

lol. bro if users have same problem. you can do bot to troubleshoot of problems but i like to look all programs open source. thanks to create this program.

**Comment by QairexStudio** [comment]
> Dürüst olmak gerekirse tüm kullanıcıların sorunlarını gidermek için çok tembelim, sadece eğlenmek için bunu yapıyorum.

**Comment by QairexStudio** [comment]
> Herhangi bir VPN / Proxy tarayıcı uzantısının tamamen **devre dışı** olduğundan emin olun . Uzantı kapalı olsa bile, yine de 'Müdahale İstemcisi' adımına müdahale edebilir.



> Make sure any VPN/Proxy browser extension is completely **disabled**. Even if the extension is just off, it could still interfere with the 'Intercepting Client' step.

im wasnt have VPN/Proxy but i changed my DNS adress at before.

**Comment by QairexStudio** [comment]
i was disable my VPN/Proxy applications but that still continue the problem.

**Comment by QairexStudio** [comment]
> I'm too lazy to troubleshoot the problems of all the users honestly, I just do this for fun.

idiot

**Comment by ArachisH** [comment]
> > I'm too lazy to troubleshoot the problems of all the users honestly, I just do this for fun.
> 
> idiot

No need for that, like I said before, this is a hobby and not my job. It's unfortunate that you can't get it to work on your machine, but it seems to work as intended for the majority of users and I'm satisfied with that.

**Comment by QairexStudio** [comment]
> > > I'm too lazy to troubleshoot the problems of all the users honestly, I just do this for fun.
> > 
> > 
> > idiot
> 
> No need for that, like I said before, this is a hobby and not my job. It's unfortunate that you can't get it to work on your machine, but it seems to work as intended for the majority of users and I'm satisfied with that.

Damn. i was exhanged mu OS. not working on linux so anymore i dont wanna use thanks.
