### ISSUE TITLE
autoban tanji

### ISSUE THREAD

**Issue by HeroinGyrl** [ArachisH/Tanji#33]
some hotels has a autoban when using tanji.
is there any way to bypass it?

**Comment by ArachisH** [comment]
No clue, depends on the methods that retro is using. If retros are intentionally banning players using Tanji then there is nothing I can really do besides applying a temporary fix, since they'll just work around it again.

**Comment by HeroinGyrl** [comment]
it's not manually banning people. when the client is injecting. the packets window is shown. but after 1-2 seconds it will autoban someone. maybe there is a packet from tanji. thats only used from tanji. that they blocked this.

**Comment by ArachisH** [comment]
G-Earth utilizes a memory scan/edit approach to achieve a MITM state by snatching the clients RC4 key when it's initialized. Tanji relies on multiple methods to reach this state through HTTPS sniffing, and client modifications.

It is much easier to break Tanji intentionally compared to G-Earth.

**Comment by HeroinGyrl** [comment]
well. would be great if you can implement the same way as G-Earth is doing it.

**Comment by Speaqer** [comment]
We won't do that because client modification gives us much easier control over the client than a memory search/edit. Just use G-Earth for retros if you're not happy with Tanji.

**Comment by HeroinGyrl** [comment]
I m very happy with tanji.

tanji is much better then every other packet logger. 
but the problem is that autoban thing.

**Comment by sirjonasxx** [comment]
My feelings...

**Comment by HeroinGyrl** [comment]
> 
> 
> My feelings...

but the reason is tanji has so much options.
currently G-Earth is the only that does not autoban. probs for that ;D

**Comment by sirjonasxx** [comment]
No just stop, I was just beginning to like you and now you pull this crap on me -,- Our friendship is over
