### ISSUE TITLE
tanji freezing

### ISSUE THREAD

**Issue by uasd12** [ArachisH/Tanji#44]
tanji is freezing with the extension falling furni ffbot 3.3.0  and other extensions

**Comment by uasd12** [comment]
after awhile playing lets say for half an hour tanji begins to freeze and the game begins to get laggy and im unable to play or interact with the program

**Comment by Speaqer** [comment]
Cannot replicate on properly developed extension, so it seems to be issue in the extensions that you are using. Tanji stays smooth and responsive for me, even if I have multiple extensions running for days. I'll be closing this issue in few days as it seems to be unrelated to Tanji.
