### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Prixm** [ArachisH/Tanji#6]
It stops working as soon as I opened it. This is the problem signatures.

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	tanji.exe
  Problem Signature 02:	1.2.6.0
  Problem Signature 03:	55e91370
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.0.30319.17929
  Problem Signature 06:	4ffa561c
  Problem Signature 07:	43c4
  Problem Signature 08:	13c
  Problem Signature 09:	System.UnauthorizedAccess
  OS Version:	6.1.7600.2.0.0.256.1
  Locale ID:	1086
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e78

**Comment by Prixm** [comment]
and yes, I've ran it as administrator.

**Comment by ArachisH** [comment]
Are you running WinXP?

**Comment by Adversities** [comment]
He running W7

**Comment by ArachisH** [comment]
Can I ask where you're extracting Tanji to? It seems it is not being allowed to create files/folders in the directory you're placing it in. Also, did previouls Tanji builds not bring this error up, or is this the only one that does?

**Comment by Prixm** [comment]
Well this problem occurs on win7 32bit. I extracted it on the desktop and I
have no problem running previous version of tanji which is tanji v0.1.

Also, I ran tanji on win8 64bit. I extracted it on the dekstop too and I
have problem opening it, it doesn't open even when i ran it as admin. And
yes, when I use tanji v0.1, I can run it wonderfully on my win8.

Thank you for you concern on replying.

**Comment by Prixm** [comment]
[image: Inline image 1]

**Comment by Prixm** [comment]
![tanji error](https://cloud.githubusercontent.com/assets/14121768/9704280/2ad9c19e-54d3-11e5-8d5f-cec3827249cf.png)

**Comment by ArachisH** [comment]
Sorry for the late response, I've recently added something to Tanji 1.3.0 to show a more descriptive error message when an uncaught exception is thrown. The update might be available during or, before this weekend.

I was unable to reproduce this error on my machine, so the only option left is to wait for the next update and hopefully a more descriptive error message is shown, or better, you get no errors.

Sorry for making you wait, but this is the best I could do with my free time.

**Comment by tomanocu** [comment]
My tanji this Giving desconect is only connected for 20 minutes at most and gives desconect

**Comment by Prixm** [comment]
Thanks for the new release, it solved my issues :)
