### ISSUE TITLE
Support Retro

### ISSUE THREAD

**Issue by Markones** [ArachisH/Tanji#7]
Hello, have you news for support Hlove.fr and Fresh-Hotel.org

**Comment by ArachisH** [comment]
I will try to make Tanji more friendly for users to connect to various other retros, but not everything can be done automatically, it will require the user to input a host/port pair prior to connecting.

I will try to add this in for the next update.

**Comment by Markones** [comment]
Hello ArachisH still not fixed on Hlove.fr !
