### ISSUE TITLE
Why is there no linux version?

### ISSUE THREAD

**Issue by elgamer334** [ArachisH/Tanji#9]
i need a linux version i dont have a cd of windows to go to win xp and i can help to build it in c (not c#)

**Comment by ArachisH** [comment]
1. There is no Linux version because I don't get payed enough to make one.
2.  You can go ahead and port this project in C, but I won't be able to help you, sorry.
3. Unfortunately, because Tanji is targeting .NET 4.5+ it will not even be able to run on WinXP machines.

**Comment by ovflowd** [comment]
Hey @arachish want help to .net core port?
